name: AmedasMap
options:
  deploymentTarget:
    iOS: "14.0"
  bundleIdPrefix: jp.tasshy

settings:
  base:
    DEVELOPMENT_TEAM: 97JN7SJ3KH

targets:
  AmedasMap:
    type: application
    platform: iOS
    sources:
      - AmedasMap


  AmedasMapTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AmedasMapTests
    dependencies:
      - target: AmedasMap

  AmedasMapUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - AmedasMapUITests
    dependencies:
      - target:	AmedasMap

